# Model arguments

model_name_or_path: HuggingFaceTB/SmolLM-1.7B

model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_mixer:
  lamm-mit/lamm-mit/bio-silk-mech-mix-80: 1.0 
  lamm-mit/raw_text_bio_marker: 1.0
  lamm-mit/raw_text_silk_marker: 1.0 
  lamm-mit/lamm-mit/bio-silk-mech-mix-80: 1.0 
  lamm-mit/bio-materials-text-60K: 1.0
  
dataset_splits:
  - train
#dataset_configs:
#  - tiny
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
dataset_kwargs:
  add_special_tokens: true  # We already wrap <bos> and <eos> in the chat template
  append_concat_token: false # No need to add <eos> across samples
do_eval: False
eval_strategy: "no"
max_grad_norm: 1.0
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: lamm-mit/SmolLM_BioSilk-CPT
hub_private_repo: True
hub_strategy: every_save
learning_rate: 5.0e-5 #2.0e-05  was before
log_level: info
logging_steps: 5 
logging_strategy: steps
lr_scheduler_type: constant
max_seq_length: 2048
max_steps: -1
num_train_epochs: 2
output_dir: data/SmolLM_BioSilk-CPT
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 6
push_to_hub: true
remove_unused_columns: true
report_to:
- wandb
#save_strategy: "steps"
#save_steps: 100

save_strategy: epoch
hub_strategy: every_save

save_total_limit: 1
seed: 42
warmup_ratio: 0.1
