# Model arguments
model_name_or_path: lamm-mit/SmolLM_BioSilk-CPT
model_revision: main
tokenizer_name_or_path: lamm-mit/HuggingFaceTB-SmolLM-1.7B-Instruct # Custom tokenizer with <|im_start|> and <|im_end|> tokens
#chat_template: "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + (message['content'] or '') + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"

torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  HuggingFaceTB/Magpie-Pro-300K-Filtered-H4: 1.0 
  HuggingFaceTB/self-oss-instruct-sc2-H4: 1.0 
  HuggingFaceTB/OpenHermes-2.5-H4: 0.001 
  HuggingFaceTB/everyday-conversations-llama3.1-2k: 1.0 
  HuggingFaceTB/instruct-data-basics-smollm-H4: 1.0 
  lamm-mit/bio-silk-mech-mix-q-a-35K-sft: 1.0
  
dataset_splits:
- train_sft
- test_sft

preprocessing_num_workers: 32

# SFT trainer config
bf16: true
dataset_kwargs:
  add_special_tokens: false  # We already wrap <bos> and <eos> in the chat template
  append_concat_token: false # No need to add <eos> across samples
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: lamm-mit/SmolLM_BioSilk-CPT-SFT
hub_strategy: every_save
learning_rate: 2.0e-05 
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 5
output_dir: data/SmolLM_BioSilk-CPT-SFT
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 6
push_to_hub: true
remove_unused_columns: true
report_to:
- wandb

save_strategy: epoch
hub_strategy: every_save

seed: 42
warmup_ratio: 0.1