# Model arguments
model_name_or_path: lamm-mit/BioSilk_Llama3.1-8b-Instruct-CPT
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

dataset_mixer:
  lamm-mit/HuggingFaceH4-ultrachat_200k: 1.0
  lamm-mit/bio-silk-mech-mix-q-a-35K: 1.0

dataset_splits:
- train
#- test_sft
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
dataset_kwargs:
  add_special_tokens: false  # We already wrap <bos> and <eos> in the chat template
  append_concat_token: false # No need to add <eos> across samples
do_eval: false

eval_strategy: "no"
max_grad_norm: 1.0
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: lamm-mit/BioSilk_Llama3.1-8b-Instruct-CPT-SFT
hub_strategy: every_save
hub_private_repo: True
learning_rate: 2.0e-05
log_level: info
logging_steps: 10  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 3076
max_steps: -1
num_train_epochs: 1
output_dir: data/BioSilk_Llama3.1-8b-Instruct-CPT-SFT
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 6
push_to_hub: true
remove_unused_columns: true
report_to:
- wandb

save_strategy: epoch
hub_strategy: every_save

save_total_limit: 1
seed: 42
warmup_ratio: 0.1
