# Model arguments
#model_name_or_path: lamm-mit/llama-3-1-bio-base_V1
model_name_or_path: lamm-mit/mistral-7B-v0.3-zephyr-Instruct-CPT_SFT
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments

dataset_mixer:
  lamm-mit/orpo-dpo-mix-40k: 1.0
  lamm-mit/bio-inspired-DPO: 1.0
  lamm-mit/spider-silk-DPO: 1.0
  lamm-mit/magpie-ultra-v0.1-DPO: 0.1
  
dataset_splits:
- train

preprocessing_num_workers: 8

# ORPOTrainer arguments
bf16: true

beta: 0.1
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id: lamm-mit/mistral-7B-v0.3-zephyr-Instruct-CPT_SFT_ORPO
hub_private_repo: true
learning_rate: 3.0e-06
log_level: info
logging_steps: 10

lr_scheduler_type: cosine

max_length: 3072
max_prompt_length: 2000
num_train_epochs: 3
#optim: adamw_bnb_8bit
output_dir: data/mistral-7B-v0.3-zephyr-Instruct-CPT_SFT_ORPO
per_device_eval_batch_size: 1
per_device_train_batch_size: 8

push_to_hub: true
report_to:
- wandb
 
save_strategy: epoch
hub_strategy: every_save

save_total_limit: 5
seed: 42
warmup_steps: 100